// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeU7od_mabvt6HLJJPnCg3ZbWIane139I',
    appId: '1:342734454015:web:e008b8de039dcabd55a0ca',
    messagingSenderId: '342734454015',
    projectId: 'flutter-fire-9b22c',
    authDomain: 'flutter-fire-9b22c.firebaseapp.com',
    databaseURL: 'https://flutter-fire-9b22c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-fire-9b22c.firebasestorage.app',
    measurementId: 'G-37Z26EMCZG',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcAnQhPGl5Dbc8y-6CRyorCf3WhcnQEeM',
    appId: '1:342734454015:android:dd7d81c678bd41e255a0ca',
    messagingSenderId: '342734454015',
    projectId: 'flutter-fire-9b22c',
    databaseURL: 'https://flutter-fire-9b22c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-fire-9b22c.firebasestorage.app',
  );
}
